///draw_text_outline(x,y,string,outline color,fill color,alpha)
draw_text_colour(argument0-1,argument1-1,argument2,argument3,argument3,argument3,argument3,argument5)
draw_text_colour(argument0-1,argument1+1,argument2,argument3,argument3,argument3,argument3,argument5)
draw_text_colour(argument0+1,argument1-1,argument2,argument3,argument3,argument3,argument3,argument5)
draw_text_colour(argument0+1,argument1+1,argument2,argument3,argument3,argument3,argument3,argument5)
draw_text_colour(argument0,argument1,argument2,argument4,argument4,argument4,argument4,argument5)
